# Generated by Django 2.2 on 2020-05-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200512_1921'),
        ('courses', '0003_bannercourse_coursetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='讲师'),
            preserve_default=False,
        ),
    ]
