# Generated by Django 2.2 on 2020-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200512_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='描述'),
        ),
    ]
