# Generated by Django 2.2 on 2020-05-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_courseorg_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='orname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='所属机构'),
        ),
    ]
